# Path to an uncompressed FASTA file with all chromosome sequences.
DNA: '/home/ya76/virilis_group_data/dvir-1.06/dvir1.06.fa'
GTF: '/home/ya76/virilis_group_data/dvir-1.06/dvir-annotation-r1.06.gtf'
INDEX: '/home/ya76/virilis_group_data/dvir-1.06/index/hista2'

# Path to a folder where final files will be written.
OUT_DIR: '/fs/cbsufsrv5/data1/ya76/Snakemake.Output.Folders/D.novamexicana_Tuxedo2_ggTrinity_RNAseq'
HOME_DIR: '/home/ya76/GitHub_Repositories/D.novamexicana_Tuxedo2_ggTrinity_RNAseq'
WORK_DIR: '/workdir'

# Path to database files and Trinotate home directory.
SHARED_DATABASE: '/shared_data/misc/TRINOTATE_RESOURCES/20160324/'
CUSTOM_DATABASE: '/home/ya76/virilis_group_data/dvir-1.06/dvir.proteins.fasta'
TRINOTATE_HOME: '/programs/Trinotate-3.0.0'
SQLITE: '/home/ya76/Trinotate/Trinotate.sqlite'

# Path to a JSON file with samples and their corresponding FASTQ files.
PE_SAMPLES_JSON: '/home/ya76/GitHub_Repositories/D.novamexicana_Tuxedo2_ggTrinity_RNAseq/samples_pe.json'
SE_SAMPLES_JSON: '/home/ya76/GitHub_Repositories/D.novamexicana_Tuxedo2_ggTrinity_RNAseq/samples_se.json'
FEM_SAMPLES_JSON: '/home/ya76/GitHub_Repositories/D.novamexicana_Tuxedo2_ggTrinity_RNAseq/samples_se_fem.json'

